=== tomyprawoto/Pendidikan/mhs_pendidikan/bin/mhs_pendidikan/mhs_pendidikan.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="politekpos">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="uang_kuliah"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="uang_kuliah">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="jurusan"/>
                <xs:element ref="biaya"/>
                <xs:element ref="program"/>
                <xs:element ref="akreditasi"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="jurusan">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:NCName">
                    <xs:attribute name="kode" use="required" type="xs:integer"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="biaya">
    	<xs:simpleType>
    		<xs:restriction base="xs:integer">

    			<xs:maxInclusive value="2000000"></xs:maxInclusive>
    		</xs:restriction>
    	</xs:simpleType>
    </xs:element>
    <xs:element name="program">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="study" minOccurs="1"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="study">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:NCName">
                    <xs:attribute name="kode" use="required" type="xs:integer"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="akreditasi" type="xs:NCName"/>
</xs:schema>

=== tomyprawoto/Pendidikan/mhs_pendidikan/bin/mhs_pendidikan/mhs_pendidikan.xml
<?xml version="1.0" encoding="UTF-8"?>
<politekpos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="mhs_pendidikan.xsd">
<uang_kuliah>
<jurusan kode="1">tenik_informatika</jurusan>
<biaya>1000000</biaya>
<program>
<study kode="001">D3</study>
<study kode="002">D4</study>
</program>
<akreditasi>B</akreditasi>
</uang_kuliah>
	<uang_kuliah>
		<jurusan kode="2">logistik_bisnis</jurusan>
		<biaya>1500000</biaya>
		<program>
			<study kode="001">D3</study>
			<study kode="002">D4</study>
		</program>
		<akreditasi>A</akreditasi>
</uang_kuliah>
	<uang_kuliah>
		<jurusan kode="3">manajemen_transportasi</jurusan>
		<biaya>200000</biaya>
		<program>
			<study kode="001">D3</study>
			<study kode="002">D4</study>
		</program>
		<akreditasi>B</akreditasi>
</uang_kuliah>
	<uang_kuliah>
		<jurusan kode="4">manajemen_informatika</jurusan>
		<biaya>1700000</biaya>
		<program>
			<study kode="001">D3</study>
			<study kode="002">D4</study>
		</program>
		<akreditasi>A</akreditasi>
</uang_kuliah>
			<uang_kuliah>
		<jurusan kode="5">manajemen_bisnis</jurusan>
		<biaya>1600000</biaya>
		<program>
			<study kode="001">D3</study>
			<study kode="002">D4</study>
		</program>
		<akreditasi>B</akreditasi>
</uang_kuliah>
</politekpos>
